# Needs cligen 0.9.46+

# This is a TOML config file

# NOTE : The config keywords are case-insensitive

# includes = ["ALL_CAPS"] includes file set in $ALL_CAPS env var.
# Example:
#   includes = ["LC_THEME"] # This can define aliases like: colors = "fhot5 = RED"

[color]
  switches = "RED"            # These example colors are likely very ugly to you.
  valtype = "CYAN"            # The full syntax for all these color/attr specs is..
  defaultvalue = "GREEN bold" # .. implemented in `cligen/humanUt.nim:textAttrParse`
  description = "PURPLE"      # .. `cligen/humanUt.nim:attrNames` is a good start.
  command = "bold"            # Command name in one-liners & in multi-cmd tables
  doc = "YELLOW"              # Overall documentation
  args = "RED"                # Positional args in one-liners

[render]
  singleStar = "italic     ; -italic"
  doubleStar = "bold       ; -bold"
  tripleStar = "bold italic; -bold -italic"
  singleBQuo = "underline  ; -underline"
  doubleBQuo = "inverse    ; -inverse"

[layout]
  # rowsep = "\n"  # This is the default; gap between option table rows
  colGap = 1     # colors make tighter format more tolerable
  # minlast = 16   # This is the default; min room for final column
  cols = ["clOptKeys", "clValType", "clDflVal", "clDescrip"] # The default
  # required = "NEED"       # How to render "REQUIRED" for mandatory params
  # minStrQuoting = true    # Minimize double quotes in help default values
  # trueDefaultStr = "y"    # How to render a true default value in help
  # falseDefaultStr = ""    # How to render a false default value in help
  # widthEnv = "MY_WIDTH"   # Wrap at $MY_WIDTH
  # wrapDoc = 80            # Wrap $doc-like at this column
  # wrapTable = 80          # Wrap $options-table-like at this column

[syntax] # Changing can EASILY break cfg files|script-usage of programs!
  reqSep = false        # true means below separator is NOT optional
  sepChars = [":", "="] # This is the default param-value separator
# longPrefixOk = true   # true means unique prefix is ok for long options
# stopPrefixOk = true   # true means unique prefix is ok for subcommand names

[templates]
  usageHeader = "%(underline)Usage:\n  "
  usage = "$command $args\n${doc}options:\n$options"
  usageMulti = """${doc}Usage:
  $command {SUBCMD}  [sub-command options & parameters]
where {SUBCMD} is one of:
$subcmds
$command {-h|--help} or with no args at all prints this message.
$command --help-syntax gives general cligen syntax help.
Run "$command {help SUBCMD|SUBCMD --help}" to see help for just SUBCMD.
Run "$command help" to get *comprehensive* help.${ifVersion}"""
